#!/usr/bin/bash
#
# ./build
# ./build [target]
# ./build <config> [target] ...cmake args
#
# target: all|install|clean|...
# config: Debug|Release|MinSizeRel|RelWithDebInfo
#
# you can set this variables
#     CMAKE_GENERATOR
#     CMAKE_BUILD_DIR
#     CMAKE_INSTALL_DIR
#     CMAKE_SOURCE_DIR
#     CMAKE_BUILD_TESTS

export CONFIG=Release
export BUILD_DIR=./out/build
export INSTALL_DIR=../install
export SOURCE_DIR=.
export BUILD_TESTS=ON

if [ ! -z "${CMAKE_BUILD_DIR}"     	]; then export BUILD_DIR=${CMAKE_BUILD_DIR}; fi
if [ ! -z "${CMAKE_INSTALL_DIR}" 	]; then export INSTALL_DIR=${CMAKE_INSTALL_DIR}; fi
if [ ! -z "${CMAKE_SOURCE_DIR}" 	]; then export SOURCE_DIR=${CMAKE_SOURCE_DIR}; fi
if [ ! -z "${CMAKE_BUILD_TESTS}" 	]; then export BUILD_TESTS=${CMAKE_BUILD_TESTS}; fi
if [ ! -z "$1" 						]; then export CONFIG=$1; fi

# echo CONFIG=${CONFIG}
# echo BUILD_DIR=${BUILD_DIR}
# echo INSTALL_DIR=${INSTALL_DIR}
# echo SOURCE_DIR=${SOURCE_DIR}
# echo BUILD_TESTS=${BUILD_TESTS}

if [ ! -z "${CMAKE_GENERATOR}"      ]; then  
    cmake -G "${CMAKE_GENERATOR}" -B "${BUILD_DIR}" -S "${SOURCE_DIR}" -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_DIR}" -DBUILD_TESTS:BOOL=${BUILD_TESTS}
else
    cmake -B "${BUILD_DIR}" -S "${SOURCE_DIR}" -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_DIR}" -DBUILD_TESTS:BOOL=${BUILD_TESTS}
fi

if [ ! -z "$1" ]; then
    if [ ! -z "$2" ]; then
        cmake --build "${BUILD_DIR}" --config ${CONFIG} --target $2 $3 $4 $5 $6 $7 $8 $9 ;
    else
        cmake --build "${BUILD_DIR}" --config ${CONFIG} ;
    fi
else
    cmake --build "${BUILD_DIR}" --config ${CONFIG} ;
fi

