name: CMake-Windows-Cxx14

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  # BUILD_TYPE: Release
  CMAKE_BUILD_DIR: ${{github.workspace}}/out/build
  CMAKE_INSTALL_DIR: ${{github.workspace}}/out/install
  CMAKE_CONFIG: Release
  CMAKE_BUILD_TESTS: ON

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get Latest CMake
      run: choco install cmake

    - name: Build
      run: |
        cmake -B ${{env.CMAKE_BUILD_DIR}} -DCMAKE_INSTALL_PREFIX=${{env.CMAKE_INSTALL_DIR}} -DBUILD_TESTS:BOOL=${{env.CMAKE_BUILD_TESTS}} -DCMAKE_CXX_STANDARD=14
        cmake --build ${{env.CMAKE_BUILD_DIR}} --config ${{env.CMAKE_CONFIG}}

    # - name: Install
    #   run: ./build install

    - name: Test
      working-directory: ${{env.CMAKE_BUILD_DIR}}
      run: ctest -C ${{env.CMAKE_CONFIG}}
  
